# Generated by Django 2.2.3 on 2019-07-25 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID:')),
                ('project_name', models.CharField(max_length=140, verbose_name='Project Name:')),
                ('description', models.TextField(max_length=1000, verbose_name='Project Description:')),
                ('records', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='No. Of Records:')),
            ],
            options={
                'ordering': ['-id', 'project_name'],
            },
        ),
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Generation ID')),
                ('field_name', models.CharField(default='Field#', max_length=100, verbose_name='Field Name')),
                ('data_type', models.CharField(blank=True, choices=[('sex', 'Gender'), ('age', 'Age'), ('address', 'Address'), ('pstatus', 'Parents Cohabitation'), ('medu', 'Mothers Education'), ('mjob', 'Mothers Job'), ('fedu', 'Fathers Education'), ('fjob', 'Fathers Job'), ('guardian', 'Guardian'), ('famsize', 'Family Size'), ('famrel', 'Family Relationships'), ('reason', 'Reason'), ('traveltime', 'Travel Time'), ('studytime', 'Study Time'), ('failures', 'Failures'), ('schoolsup', 'School Support'), ('famsup', 'Family Support'), ('activities', 'Extra-Curricular'), ('paidclass', 'Paid Classes'), ('internet', 'Internet Access'), ('freetime', 'Free Time'), ('walc', 'Weekend Alcohol'), ('dalc', 'Workday Alcohol'), ('health', 'Health'), ('absences', 'Absences'), ('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3')], default='sex', max_length=10, verbose_name='Data Type')),
                ('options', models.TextField(blank=True, default='Male, Female', max_length=100, verbose_name='Options')),
                ('project_id', models.ForeignKey(null=True, on_delete='Project ID', to='Synthetica.Project')),
            ],
        ),
    ]
