# Generated by Django 2.2.3 on 2019-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0002_auto_20190730_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='options',
            field=models.TextField(default='Male, Female', max_length=250, verbose_name='Options'),
        ),
    ]
