# Generated by Django 2.2.2 on 2019-07-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
