# Generated by Django 2.2.2 on 2019-07-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0002_auto_20190708_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Generation ID:')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Synthetica.Project')),
            ],
        ),
    ]
