# Generated by Django 2.2.2 on 2019-07-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0004_auto_20190708_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='data_type',
            field=models.CharField(blank=True, choices=[('t', 'Short Text'), ('n', 'Numeric'), ('a', 'Alphanumeric'), ('lt', 'Long Text')], default='t', max_length=2, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='generate',
            name='options',
            field=models.TextField(blank=True, default='1,2,3', max_length=100, verbose_name='Options:'),
        ),
    ]
