# Generated by Django 2.2.2 on 2019-07-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0005_auto_20190708_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate',
            old_name='project_id',
            new_name='project_name',
        ),
    ]
