# Generated by Django 2.2.2 on 2019-07-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0006_auto_20190708_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate',
            old_name='project_name',
            new_name='project_id',
        ),
    ]
