# Generated by Django 2.2.2 on 2019-07-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0007_auto_20190709_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generate',
        ),
    ]
