# Generated by Django 2.2.2 on 2019-07-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0008_delete_generate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
