# Generated by Django 2.2.2 on 2019-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Synthetica', '0009_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID:')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name:')),
                ('description', models.TextField(max_length=1500, verbose_name='Project Description:')),
                ('attributes', models.IntegerField(default=1, verbose_name='No. Of Attributes:')),
                ('rows', models.IntegerField(default=1, verbose_name='No. Of Rows:')),
            ],
        ),
    ]
