# Generated by Django 2.2.2 on 2019-07-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0010_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Generation ID:')),
                ('data_type', models.CharField(blank=True, choices=[('t', 'Short Text'), ('n', 'Numeric'), ('a', 'Alphanumeric'), ('lt', 'Long Text')], default='t', max_length=2, verbose_name='Data Type')),
                ('options', models.TextField(blank=True, default='1,2,3', max_length=100, verbose_name='Options:')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Synthetica.Project')),
            ],
        ),
    ]
