# Generated by Django 2.2.2 on 2019-07-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0012_auto_20190709_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generate',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
