# Generated by Django 2.2.2 on 2019-07-12 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Synthetica', '0013_auto_20190712_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID:')),
                ('project_name', models.CharField(max_length=100, verbose_name='Project Name:')),
                ('description', models.TextField(max_length=1000, verbose_name='Project Description:')),
                ('attributes', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='No. Of Attributes:')),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='No. Of Rows:')),
            ],
            options={
                'ordering': ['-id', 'project_name'],
            },
        ),
    ]
