# Generated by Django 2.2.2 on 2019-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0014_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Generation ID:')),
                ('data_type', models.CharField(blank=True, choices=[('t', 'Short Text'), ('n', 'Numeric'), ('a', 'Alphanumeric'), ('lt', 'Long Text'), ('d', 'Date'), ('ti', 'Time'), ('dti', 'Date & Time')], default='t', max_length=2, verbose_name='Data Type')),
                ('options', models.TextField(blank=True, default='car, shoe, tree', max_length=100, verbose_name='Options:')),
                ('project_name', models.ForeignKey(null=True, on_delete='Project Name:', to='Synthetica.Project')),
            ],
        ),
    ]
