# Generated by Django 2.2.2 on 2019-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0015_generate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate',
            name='project_name',
        ),
        migrations.AddField(
            model_name='generate',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete='Project ID:', to='Synthetica.Project'),
        ),
    ]
