# Generated by Django 2.2.2 on 2019-07-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0016_auto_20190712_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate',
            old_name='project_id',
            new_name='project_name',
        ),
    ]
