# Generated by Django 2.2.2 on 2019-07-17 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0017_auto_20190712_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate',
            old_name='project_name',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rows',
        ),
        migrations.AddField(
            model_name='project',
            name='records',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='No. Of Records:'),
        ),
        migrations.AlterField(
            model_name='generate',
            name='data_type',
            field=models.CharField(blank=True, choices=[('t', 'Short Text'), ('n', 'Numeric'), ('a', 'Alphanumeric'), ('lt', 'Long Text'), ('d', 'Date'), ('ti', 'Time'), ('dti', 'Date & Time')], default='t', max_length=3, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='generate',
            name='options',
            field=models.TextField(blank=True, default='car, shoe, tree', max_length=100, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=140, verbose_name='Project Name:'),
        ),
    ]
