# Generated by Django 2.2.2 on 2019-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0018_auto_20190717_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate',
            name='field_name',
            field=models.CharField(default='Field#', max_length=100, verbose_name='Field Name:'),
        ),
    ]
