# Generated by Django 2.2.2 on 2019-07-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synthetica', '0019_generate_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='field_name',
            field=models.CharField(default='Field#', max_length=100, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='generate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Generation ID'),
        ),
        migrations.AlterField(
            model_name='generate',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete='Project ID', to='Synthetica.Project'),
        ),
    ]
